//------------------------------------------------------------------------------
// <auto-generated>
//     O código foi gerado por uma ferramenta.
//     Versão de Tempo de Execução:4.0.30319.42000
//
//     As alterações ao arquivo poderão causar comportamento incorreto e serão perdidas se
//     o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Script
{
    using System;
    using System.Xml;
    using System.Xml.Schema;
    using System.Collections.Generic;
    using HP.ST.Fwk.RunTimeFWK;
    using HP.ST.Fwk.RunTimeFWK.CheckpointFWK;
    using HP.ST.Fwk.RunTimeFWK.Utilities;
    using HP.ST.Ext.CheckpointLogicOperators;
    using HP.ST.Ext.BindingImpl.Getters;
    using HP.ST.Ext.BindingImpl.Setters;
    using HP.ST.Fwk.RunTimeFWK.BindingFWK;
    using HP.ST.Fwk.RunTimeFWK.BindingFWK.Getters;
    using HP.ST.Fwk.RunTimeFWK.BindingFWK.Setters;
    using HP.ST.Fwk.RunTimeFWK.BindingFWK.PropInfo;
    using HP.ST.Ext.CheckpointRules.ArrayCheckpoints;
    
    
    public partial class WorkFlowScript
    {
        
        private void set_HTTPActivity4_checkpoints(STActivityBase activity)
        {
            // Checkpoint 1
            IVTDGetter actualValueGetter1 = new VTDXPathGetter(new VTDPropertyInfoBase("XMLResponse", "count(/*[local-name(.)='Array'][1]/*[local-name(.)='Object'])"), XmlTypeCode.None, false);
            IVTDSetter actualValueSetter1 = new VTDCheckpointSetter(XmlTypeCode.Double);
            BindDirection actualBindDirection1 = new BindDirection(_flow.HTTPActivity4, actualValueGetter1, actualValueSetter1);
            CpValObj valueActualObject1 = new CpValObj(actualBindDirection1, XmlTypeCode.Double, false);
            CpValObj valueExpectedObject1 = new CpValObj("10", XmlTypeCode.Double);
            ValueCPRule cpRule1 = new ValueCPRule(valueActualObject1, valueExpectedObject1, PrimitiveTypeCP.EqualTo, "=", false);
            activity.AddCheckpointRule(cpRule1);

            // Checkpoint 2
            IVTDGetter actualValueGetter2 = new VTDXPathGetter(new VTDPropertyInfoBase("XMLResponse", "/*[local-name(.)='Array'][1]/*[local-name(.)='Object'][1]/*[local-name(.)='id'][1]"), XmlTypeCode.UnsignedInt, false);
            IVTDSetter actualValueSetter2 = new VTDCheckpointSetter(XmlTypeCode.UnsignedInt);
            BindDirection actualBindDirection2 = new BindDirection(_flow.HTTPActivity4, actualValueGetter2, actualValueSetter2);
            CpValObj valueActualObject2 = new CpValObj(actualBindDirection2, XmlTypeCode.UnsignedInt, false);
            CpValObj valueExpectedObject2 = new CpValObj("5816791", XmlTypeCode.UnsignedInt);
            ValueCPRule cpRule2 = new ValueCPRule(valueActualObject2, valueExpectedObject2, PrimitiveTypeCP.EqualTo, "=", false);

            // Checkpoint 3
            IVTDGetter actualValueGetter3 = new VTDXPathGetter(new VTDPropertyInfoBase("XMLResponse", "/*[local-name(.)='Array'][1]/*[local-name(.)='Object'][1]/*[local-name(.)='name'][1]"), XmlTypeCode.String, false);
            IVTDSetter actualValueSetter3 = new VTDCheckpointSetter(XmlTypeCode.String);
            BindDirection actualBindDirection3 = new BindDirection(_flow.HTTPActivity4, actualValueGetter3, actualValueSetter3);
            CpValObj valueActualObject3 = new CpValObj(actualBindDirection3, XmlTypeCode.String, false);
            CpValObj valueExpectedObject3 = new CpValObj("Marut Ganaka", XmlTypeCode.String);
            ValueCPRule cpRule3 = new ValueCPRule(valueActualObject3, valueExpectedObject3, StringCP.EqualTo, "=", false);

            // Checkpoint 4
            IVTDGetter actualValueGetter4 = new VTDXPathGetter(new VTDPropertyInfoBase("XMLResponse", "/*[local-name(.)='Array'][1]/*[local-name(.)='Object'][1]/*[local-name(.)='email'][1]"), XmlTypeCode.String, false);
            IVTDSetter actualValueSetter4 = new VTDCheckpointSetter(XmlTypeCode.String);
            BindDirection actualBindDirection4 = new BindDirection(_flow.HTTPActivity4, actualValueGetter4, actualValueSetter4);
            CpValObj valueActualObject4 = new CpValObj(actualBindDirection4, XmlTypeCode.String, false);
            CpValObj valueExpectedObject4 = new CpValObj("marut_ganaka@schiller.test", XmlTypeCode.String);
            ValueCPRule cpRule4 = new ValueCPRule(valueActualObject4, valueExpectedObject4, StringCP.EqualTo, "=", false);

            // Checkpoint 5
            IVTDGetter actualValueGetter5 = new VTDXPathGetter(new VTDPropertyInfoBase("XMLResponse", "/*[local-name(.)='Array'][1]/*[local-name(.)='Object'][1]/*[local-name(.)='gender'][1]"), XmlTypeCode.String, false);
            IVTDSetter actualValueSetter5 = new VTDCheckpointSetter(XmlTypeCode.String);
            BindDirection actualBindDirection5 = new BindDirection(_flow.HTTPActivity4, actualValueGetter5, actualValueSetter5);
            CpValObj valueActualObject5 = new CpValObj(actualBindDirection5, XmlTypeCode.String, false);
            CpValObj valueExpectedObject5 = new CpValObj("female", XmlTypeCode.String);
            ValueCPRule cpRule5 = new ValueCPRule(valueActualObject5, valueExpectedObject5, StringCP.EqualTo, "=", false);

            // Checkpoint 6
            IVTDGetter actualValueGetter6 = new VTDXPathGetter(new VTDPropertyInfoBase("XMLResponse", "/*[local-name(.)='Array'][1]/*[local-name(.)='Object'][1]/*[local-name(.)='status'][1]"), XmlTypeCode.String, false);
            IVTDSetter actualValueSetter6 = new VTDCheckpointSetter(XmlTypeCode.String);
            BindDirection actualBindDirection6 = new BindDirection(_flow.HTTPActivity4, actualValueGetter6, actualValueSetter6);
            CpValObj valueActualObject6 = new CpValObj(actualBindDirection6, XmlTypeCode.String, false);
            CpValObj valueExpectedObject6 = new CpValObj("active", XmlTypeCode.String);
            ValueCPRule cpRule6 = new ValueCPRule(valueActualObject6, valueExpectedObject6, StringCP.EqualTo, "=", false);

            // Checkpoint 7
            IVTDGetter actualValueGetter7 = new VTDXPathGetter(new VTDPropertyInfoBase("XMLResponse", "/*[local-name(.)='Array'][1]/*[local-name(.)='Object'][2]/*[local-name(.)='id'][1]"), XmlTypeCode.UnsignedInt, false);
            IVTDSetter actualValueSetter7 = new VTDCheckpointSetter(XmlTypeCode.UnsignedInt);
            BindDirection actualBindDirection7 = new BindDirection(_flow.HTTPActivity4, actualValueGetter7, actualValueSetter7);
            CpValObj valueActualObject7 = new CpValObj(actualBindDirection7, XmlTypeCode.UnsignedInt, false);
            CpValObj valueExpectedObject7 = new CpValObj("5816790", XmlTypeCode.UnsignedInt);
            ValueCPRule cpRule7 = new ValueCPRule(valueActualObject7, valueExpectedObject7, PrimitiveTypeCP.EqualTo, "=", false);

            // Checkpoint 8
            IVTDGetter actualValueGetter8 = new VTDXPathGetter(new VTDPropertyInfoBase("XMLResponse", "/*[local-name(.)='Array'][1]/*[local-name(.)='Object'][2]/*[local-name(.)='name'][1]"), XmlTypeCode.String, false);
            IVTDSetter actualValueSetter8 = new VTDCheckpointSetter(XmlTypeCode.String);
            BindDirection actualBindDirection8 = new BindDirection(_flow.HTTPActivity4, actualValueGetter8, actualValueSetter8);
            CpValObj valueActualObject8 = new CpValObj(actualBindDirection8, XmlTypeCode.String, false);
            CpValObj valueExpectedObject8 = new CpValObj("Nirbhay Malik Sr.", XmlTypeCode.String);
            ValueCPRule cpRule8 = new ValueCPRule(valueActualObject8, valueExpectedObject8, StringCP.EqualTo, "=", false);

            // Checkpoint 9
            IVTDGetter actualValueGetter9 = new VTDXPathGetter(new VTDPropertyInfoBase("XMLResponse", "/*[local-name(.)='Array'][1]/*[local-name(.)='Object'][2]/*[local-name(.)='email'][1]"), XmlTypeCode.String, false);
            IVTDSetter actualValueSetter9 = new VTDCheckpointSetter(XmlTypeCode.String);
            BindDirection actualBindDirection9 = new BindDirection(_flow.HTTPActivity4, actualValueGetter9, actualValueSetter9);
            CpValObj valueActualObject9 = new CpValObj(actualBindDirection9, XmlTypeCode.String, false);
            CpValObj valueExpectedObject9 = new CpValObj("sr_malik_nirbhay@lang.example", XmlTypeCode.String);
            ValueCPRule cpRule9 = new ValueCPRule(valueActualObject9, valueExpectedObject9, StringCP.EqualTo, "=", false);

            // Checkpoint 10
            IVTDGetter actualValueGetter10 = new VTDXPathGetter(new VTDPropertyInfoBase("XMLResponse", "/*[local-name(.)='Array'][1]/*[local-name(.)='Object'][2]/*[local-name(.)='gender'][1]"), XmlTypeCode.String, false);
            IVTDSetter actualValueSetter10 = new VTDCheckpointSetter(XmlTypeCode.String);
            BindDirection actualBindDirection10 = new BindDirection(_flow.HTTPActivity4, actualValueGetter10, actualValueSetter10);
            CpValObj valueActualObject10 = new CpValObj(actualBindDirection10, XmlTypeCode.String, false);
            CpValObj valueExpectedObject10 = new CpValObj("male", XmlTypeCode.String);
            ValueCPRule cpRule10 = new ValueCPRule(valueActualObject10, valueExpectedObject10, StringCP.EqualTo, "=", false);

            // Checkpoint 11
            IVTDGetter actualValueGetter11 = new VTDXPathGetter(new VTDPropertyInfoBase("XMLResponse", "/*[local-name(.)='Array'][1]/*[local-name(.)='Object'][2]/*[local-name(.)='status'][1]"), XmlTypeCode.String, false);
            IVTDSetter actualValueSetter11 = new VTDCheckpointSetter(XmlTypeCode.String);
            BindDirection actualBindDirection11 = new BindDirection(_flow.HTTPActivity4, actualValueGetter11, actualValueSetter11);
            CpValObj valueActualObject11 = new CpValObj(actualBindDirection11, XmlTypeCode.String, false);
            CpValObj valueExpectedObject11 = new CpValObj("inactive", XmlTypeCode.String);
            ValueCPRule cpRule11 = new ValueCPRule(valueActualObject11, valueExpectedObject11, StringCP.EqualTo, "=", false);

            // Checkpoint 12
            IVTDGetter actualValueGetter12 = new VTDXPathGetter(new VTDPropertyInfoBase("XMLResponse", "/*[local-name(.)='Array'][1]/*[local-name(.)='Object'][3]/*[local-name(.)='id'][1]"), XmlTypeCode.UnsignedInt, false);
            IVTDSetter actualValueSetter12 = new VTDCheckpointSetter(XmlTypeCode.UnsignedInt);
            BindDirection actualBindDirection12 = new BindDirection(_flow.HTTPActivity4, actualValueGetter12, actualValueSetter12);
            CpValObj valueActualObject12 = new CpValObj(actualBindDirection12, XmlTypeCode.UnsignedInt, false);
            CpValObj valueExpectedObject12 = new CpValObj("5816789", XmlTypeCode.UnsignedInt);
            ValueCPRule cpRule12 = new ValueCPRule(valueActualObject12, valueExpectedObject12, PrimitiveTypeCP.EqualTo, "=", false);

            // Checkpoint 13
            IVTDGetter actualValueGetter13 = new VTDXPathGetter(new VTDPropertyInfoBase("XMLResponse", "/*[local-name(.)='Array'][1]/*[local-name(.)='Object'][3]/*[local-name(.)='name'][1]"), XmlTypeCode.String, false);
            IVTDSetter actualValueSetter13 = new VTDCheckpointSetter(XmlTypeCode.String);
            BindDirection actualBindDirection13 = new BindDirection(_flow.HTTPActivity4, actualValueGetter13, actualValueSetter13);
            CpValObj valueActualObject13 = new CpValObj(actualBindDirection13, XmlTypeCode.String, false);
            CpValObj valueExpectedObject13 = new CpValObj("Aalok Dhawan DC", XmlTypeCode.String);
            ValueCPRule cpRule13 = new ValueCPRule(valueActualObject13, valueExpectedObject13, StringCP.EqualTo, "=", false);

            // Checkpoint 14
            IVTDGetter actualValueGetter14 = new VTDXPathGetter(new VTDPropertyInfoBase("XMLResponse", "/*[local-name(.)='Array'][1]/*[local-name(.)='Object'][3]/*[local-name(.)='email'][1]"), XmlTypeCode.String, false);
            IVTDSetter actualValueSetter14 = new VTDCheckpointSetter(XmlTypeCode.String);
            BindDirection actualBindDirection14 = new BindDirection(_flow.HTTPActivity4, actualValueGetter14, actualValueSetter14);
            CpValObj valueActualObject14 = new CpValObj(actualBindDirection14, XmlTypeCode.String, false);
            CpValObj valueExpectedObject14 = new CpValObj("dc_aalok_dhawan@hammes.example", XmlTypeCode.String);
            ValueCPRule cpRule14 = new ValueCPRule(valueActualObject14, valueExpectedObject14, StringCP.EqualTo, "=", false);

            // Checkpoint 15
            IVTDGetter actualValueGetter15 = new VTDXPathGetter(new VTDPropertyInfoBase("XMLResponse", "/*[local-name(.)='Array'][1]/*[local-name(.)='Object'][3]/*[local-name(.)='gender'][1]"), XmlTypeCode.String, false);
            IVTDSetter actualValueSetter15 = new VTDCheckpointSetter(XmlTypeCode.String);
            BindDirection actualBindDirection15 = new BindDirection(_flow.HTTPActivity4, actualValueGetter15, actualValueSetter15);
            CpValObj valueActualObject15 = new CpValObj(actualBindDirection15, XmlTypeCode.String, false);
            CpValObj valueExpectedObject15 = new CpValObj("male", XmlTypeCode.String);
            ValueCPRule cpRule15 = new ValueCPRule(valueActualObject15, valueExpectedObject15, StringCP.EqualTo, "=", false);

            // Checkpoint 16
            IVTDGetter actualValueGetter16 = new VTDXPathGetter(new VTDPropertyInfoBase("XMLResponse", "/*[local-name(.)='Array'][1]/*[local-name(.)='Object'][3]/*[local-name(.)='status'][1]"), XmlTypeCode.String, false);
            IVTDSetter actualValueSetter16 = new VTDCheckpointSetter(XmlTypeCode.String);
            BindDirection actualBindDirection16 = new BindDirection(_flow.HTTPActivity4, actualValueGetter16, actualValueSetter16);
            CpValObj valueActualObject16 = new CpValObj(actualBindDirection16, XmlTypeCode.String, false);
            CpValObj valueExpectedObject16 = new CpValObj("active", XmlTypeCode.String);
            ValueCPRule cpRule16 = new ValueCPRule(valueActualObject16, valueExpectedObject16, StringCP.EqualTo, "=", false);

            // Checkpoint 17
            IVTDGetter actualValueGetter17 = new VTDXPathGetter(new VTDPropertyInfoBase("XMLResponse", "/*[local-name(.)='Array'][1]/*[local-name(.)='Object'][4]/*[local-name(.)='id'][1]"), XmlTypeCode.UnsignedInt, false);
            IVTDSetter actualValueSetter17 = new VTDCheckpointSetter(XmlTypeCode.UnsignedInt);
            BindDirection actualBindDirection17 = new BindDirection(_flow.HTTPActivity4, actualValueGetter17, actualValueSetter17);
            CpValObj valueActualObject17 = new CpValObj(actualBindDirection17, XmlTypeCode.UnsignedInt, false);
            CpValObj valueExpectedObject17 = new CpValObj("5816787", XmlTypeCode.UnsignedInt);
            ValueCPRule cpRule17 = new ValueCPRule(valueActualObject17, valueExpectedObject17, PrimitiveTypeCP.EqualTo, "=", false);

            // Checkpoint 18
            IVTDGetter actualValueGetter18 = new VTDXPathGetter(new VTDPropertyInfoBase("XMLResponse", "/*[local-name(.)='Array'][1]/*[local-name(.)='Object'][4]/*[local-name(.)='name'][1]"), XmlTypeCode.String, false);
            IVTDSetter actualValueSetter18 = new VTDCheckpointSetter(XmlTypeCode.String);
            BindDirection actualBindDirection18 = new BindDirection(_flow.HTTPActivity4, actualValueGetter18, actualValueSetter18);
            CpValObj valueActualObject18 = new CpValObj(actualBindDirection18, XmlTypeCode.String, false);
            CpValObj valueExpectedObject18 = new CpValObj("Sucheta Asan", XmlTypeCode.String);
            ValueCPRule cpRule18 = new ValueCPRule(valueActualObject18, valueExpectedObject18, StringCP.EqualTo, "=", false);

            // Checkpoint 19
            IVTDGetter actualValueGetter19 = new VTDXPathGetter(new VTDPropertyInfoBase("XMLResponse", "/*[local-name(.)='Array'][1]/*[local-name(.)='Object'][4]/*[local-name(.)='email'][1]"), XmlTypeCode.String, false);
            IVTDSetter actualValueSetter19 = new VTDCheckpointSetter(XmlTypeCode.String);
            BindDirection actualBindDirection19 = new BindDirection(_flow.HTTPActivity4, actualValueGetter19, actualValueSetter19);
            CpValObj valueActualObject19 = new CpValObj(actualBindDirection19, XmlTypeCode.String, false);
            CpValObj valueExpectedObject19 = new CpValObj("asan_sucheta@moen-satterfield.example", XmlTypeCode.String);
            ValueCPRule cpRule19 = new ValueCPRule(valueActualObject19, valueExpectedObject19, StringCP.EqualTo, "=", false);

            // Checkpoint 20
            IVTDGetter actualValueGetter20 = new VTDXPathGetter(new VTDPropertyInfoBase("XMLResponse", "/*[local-name(.)='Array'][1]/*[local-name(.)='Object'][4]/*[local-name(.)='gender'][1]"), XmlTypeCode.String, false);
            IVTDSetter actualValueSetter20 = new VTDCheckpointSetter(XmlTypeCode.String);
            BindDirection actualBindDirection20 = new BindDirection(_flow.HTTPActivity4, actualValueGetter20, actualValueSetter20);
            CpValObj valueActualObject20 = new CpValObj(actualBindDirection20, XmlTypeCode.String, false);
            CpValObj valueExpectedObject20 = new CpValObj("female", XmlTypeCode.String);
            ValueCPRule cpRule20 = new ValueCPRule(valueActualObject20, valueExpectedObject20, StringCP.EqualTo, "=", false);

            // Checkpoint 21
            IVTDGetter actualValueGetter21 = new VTDXPathGetter(new VTDPropertyInfoBase("XMLResponse", "/*[local-name(.)='Array'][1]/*[local-name(.)='Object'][4]/*[local-name(.)='status'][1]"), XmlTypeCode.String, false);
            IVTDSetter actualValueSetter21 = new VTDCheckpointSetter(XmlTypeCode.String);
            BindDirection actualBindDirection21 = new BindDirection(_flow.HTTPActivity4, actualValueGetter21, actualValueSetter21);
            CpValObj valueActualObject21 = new CpValObj(actualBindDirection21, XmlTypeCode.String, false);
            CpValObj valueExpectedObject21 = new CpValObj("active", XmlTypeCode.String);
            ValueCPRule cpRule21 = new ValueCPRule(valueActualObject21, valueExpectedObject21, StringCP.EqualTo, "=", false);

            // Checkpoint 22
            IVTDGetter actualValueGetter22 = new VTDXPathGetter(new VTDPropertyInfoBase("XMLResponse", "/*[local-name(.)='Array'][1]/*[local-name(.)='Object'][5]/*[local-name(.)='id'][1]"), XmlTypeCode.UnsignedInt, false);
            IVTDSetter actualValueSetter22 = new VTDCheckpointSetter(XmlTypeCode.UnsignedInt);
            BindDirection actualBindDirection22 = new BindDirection(_flow.HTTPActivity4, actualValueGetter22, actualValueSetter22);
            CpValObj valueActualObject22 = new CpValObj(actualBindDirection22, XmlTypeCode.UnsignedInt, false);
            CpValObj valueExpectedObject22 = new CpValObj("5816786", XmlTypeCode.UnsignedInt);
            ValueCPRule cpRule22 = new ValueCPRule(valueActualObject22, valueExpectedObject22, PrimitiveTypeCP.EqualTo, "=", false);

            // Checkpoint 23
            IVTDGetter actualValueGetter23 = new VTDXPathGetter(new VTDPropertyInfoBase("XMLResponse", "/*[local-name(.)='Array'][1]/*[local-name(.)='Object'][5]/*[local-name(.)='name'][1]"), XmlTypeCode.String, false);
            IVTDSetter actualValueSetter23 = new VTDCheckpointSetter(XmlTypeCode.String);
            BindDirection actualBindDirection23 = new BindDirection(_flow.HTTPActivity4, actualValueGetter23, actualValueSetter23);
            CpValObj valueActualObject23 = new CpValObj(actualBindDirection23, XmlTypeCode.String, false);
            CpValObj valueExpectedObject23 = new CpValObj("Dron Acharya", XmlTypeCode.String);
            ValueCPRule cpRule23 = new ValueCPRule(valueActualObject23, valueExpectedObject23, StringCP.EqualTo, "=", false);

            // Checkpoint 24
            IVTDGetter actualValueGetter24 = new VTDXPathGetter(new VTDPropertyInfoBase("XMLResponse", "/*[local-name(.)='Array'][1]/*[local-name(.)='Object'][5]/*[local-name(.)='email'][1]"), XmlTypeCode.String, false);
            IVTDSetter actualValueSetter24 = new VTDCheckpointSetter(XmlTypeCode.String);
            BindDirection actualBindDirection24 = new BindDirection(_flow.HTTPActivity4, actualValueGetter24, actualValueSetter24);
            CpValObj valueActualObject24 = new CpValObj(actualBindDirection24, XmlTypeCode.String, false);
            CpValObj valueExpectedObject24 = new CpValObj("dron_acharya@skiles.test", XmlTypeCode.String);
            ValueCPRule cpRule24 = new ValueCPRule(valueActualObject24, valueExpectedObject24, StringCP.EqualTo, "=", false);

            // Checkpoint 25
            IVTDGetter actualValueGetter25 = new VTDXPathGetter(new VTDPropertyInfoBase("XMLResponse", "/*[local-name(.)='Array'][1]/*[local-name(.)='Object'][5]/*[local-name(.)='gender'][1]"), XmlTypeCode.String, false);
            IVTDSetter actualValueSetter25 = new VTDCheckpointSetter(XmlTypeCode.String);
            BindDirection actualBindDirection25 = new BindDirection(_flow.HTTPActivity4, actualValueGetter25, actualValueSetter25);
            CpValObj valueActualObject25 = new CpValObj(actualBindDirection25, XmlTypeCode.String, false);
            CpValObj valueExpectedObject25 = new CpValObj("female", XmlTypeCode.String);
            ValueCPRule cpRule25 = new ValueCPRule(valueActualObject25, valueExpectedObject25, StringCP.EqualTo, "=", false);

            // Checkpoint 26
            IVTDGetter actualValueGetter26 = new VTDXPathGetter(new VTDPropertyInfoBase("XMLResponse", "/*[local-name(.)='Array'][1]/*[local-name(.)='Object'][5]/*[local-name(.)='status'][1]"), XmlTypeCode.String, false);
            IVTDSetter actualValueSetter26 = new VTDCheckpointSetter(XmlTypeCode.String);
            BindDirection actualBindDirection26 = new BindDirection(_flow.HTTPActivity4, actualValueGetter26, actualValueSetter26);
            CpValObj valueActualObject26 = new CpValObj(actualBindDirection26, XmlTypeCode.String, false);
            CpValObj valueExpectedObject26 = new CpValObj("active", XmlTypeCode.String);
            ValueCPRule cpRule26 = new ValueCPRule(valueActualObject26, valueExpectedObject26, StringCP.EqualTo, "=", false);

            // Checkpoint 27
            IVTDGetter actualValueGetter27 = new VTDXPathGetter(new VTDPropertyInfoBase("XMLResponse", "/*[local-name(.)='Array'][1]/*[local-name(.)='Object'][6]/*[local-name(.)='id'][1]"), XmlTypeCode.UnsignedInt, false);
            IVTDSetter actualValueSetter27 = new VTDCheckpointSetter(XmlTypeCode.UnsignedInt);
            BindDirection actualBindDirection27 = new BindDirection(_flow.HTTPActivity4, actualValueGetter27, actualValueSetter27);
            CpValObj valueActualObject27 = new CpValObj(actualBindDirection27, XmlTypeCode.UnsignedInt, false);
            CpValObj valueExpectedObject27 = new CpValObj("5816785", XmlTypeCode.UnsignedInt);
            ValueCPRule cpRule27 = new ValueCPRule(valueActualObject27, valueExpectedObject27, PrimitiveTypeCP.EqualTo, "=", false);

            // Checkpoint 28
            IVTDGetter actualValueGetter28 = new VTDXPathGetter(new VTDPropertyInfoBase("XMLResponse", "/*[local-name(.)='Array'][1]/*[local-name(.)='Object'][6]/*[local-name(.)='name'][1]"), XmlTypeCode.String, false);
            IVTDSetter actualValueSetter28 = new VTDCheckpointSetter(XmlTypeCode.String);
            BindDirection actualBindDirection28 = new BindDirection(_flow.HTTPActivity4, actualValueGetter28, actualValueSetter28);
            CpValObj valueActualObject28 = new CpValObj(actualBindDirection28, XmlTypeCode.String, false);
            CpValObj valueExpectedObject28 = new CpValObj("Shridevi Naik IV", XmlTypeCode.String);
            ValueCPRule cpRule28 = new ValueCPRule(valueActualObject28, valueExpectedObject28, StringCP.EqualTo, "=", false);

            // Checkpoint 29
            IVTDGetter actualValueGetter29 = new VTDXPathGetter(new VTDPropertyInfoBase("XMLResponse", "/*[local-name(.)='Array'][1]/*[local-name(.)='Object'][6]/*[local-name(.)='email'][1]"), XmlTypeCode.String, false);
            IVTDSetter actualValueSetter29 = new VTDCheckpointSetter(XmlTypeCode.String);
            BindDirection actualBindDirection29 = new BindDirection(_flow.HTTPActivity4, actualValueGetter29, actualValueSetter29);
            CpValObj valueActualObject29 = new CpValObj(actualBindDirection29, XmlTypeCode.String, false);
            CpValObj valueExpectedObject29 = new CpValObj("naik_shridevi_iv@macejkovic-west.test", XmlTypeCode.String);
            ValueCPRule cpRule29 = new ValueCPRule(valueActualObject29, valueExpectedObject29, StringCP.EqualTo, "=", false);

            // Checkpoint 30
            IVTDGetter actualValueGetter30 = new VTDXPathGetter(new VTDPropertyInfoBase("XMLResponse", "/*[local-name(.)='Array'][1]/*[local-name(.)='Object'][6]/*[local-name(.)='gender'][1]"), XmlTypeCode.String, false);
            IVTDSetter actualValueSetter30 = new VTDCheckpointSetter(XmlTypeCode.String);
            BindDirection actualBindDirection30 = new BindDirection(_flow.HTTPActivity4, actualValueGetter30, actualValueSetter30);
            CpValObj valueActualObject30 = new CpValObj(actualBindDirection30, XmlTypeCode.String, false);
            CpValObj valueExpectedObject30 = new CpValObj("male", XmlTypeCode.String);
            ValueCPRule cpRule30 = new ValueCPRule(valueActualObject30, valueExpectedObject30, StringCP.EqualTo, "=", false);

            // Checkpoint 31
            IVTDGetter actualValueGetter31 = new VTDXPathGetter(new VTDPropertyInfoBase("XMLResponse", "/*[local-name(.)='Array'][1]/*[local-name(.)='Object'][6]/*[local-name(.)='status'][1]"), XmlTypeCode.String, false);
            IVTDSetter actualValueSetter31 = new VTDCheckpointSetter(XmlTypeCode.String);
            BindDirection actualBindDirection31 = new BindDirection(_flow.HTTPActivity4, actualValueGetter31, actualValueSetter31);
            CpValObj valueActualObject31 = new CpValObj(actualBindDirection31, XmlTypeCode.String, false);
            CpValObj valueExpectedObject31 = new CpValObj("active", XmlTypeCode.String);
            ValueCPRule cpRule31 = new ValueCPRule(valueActualObject31, valueExpectedObject31, StringCP.EqualTo, "=", false);

            // Checkpoint 32
            IVTDGetter actualValueGetter32 = new VTDXPathGetter(new VTDPropertyInfoBase("XMLResponse", "/*[local-name(.)='Array'][1]/*[local-name(.)='Object'][7]/*[local-name(.)='id'][1]"), XmlTypeCode.UnsignedInt, false);
            IVTDSetter actualValueSetter32 = new VTDCheckpointSetter(XmlTypeCode.UnsignedInt);
            BindDirection actualBindDirection32 = new BindDirection(_flow.HTTPActivity4, actualValueGetter32, actualValueSetter32);
            CpValObj valueActualObject32 = new CpValObj(actualBindDirection32, XmlTypeCode.UnsignedInt, false);
            CpValObj valueExpectedObject32 = new CpValObj("5816784", XmlTypeCode.UnsignedInt);
            ValueCPRule cpRule32 = new ValueCPRule(valueActualObject32, valueExpectedObject32, PrimitiveTypeCP.EqualTo, "=", false);

            // Checkpoint 33
            IVTDGetter actualValueGetter33 = new VTDXPathGetter(new VTDPropertyInfoBase("XMLResponse", "/*[local-name(.)='Array'][1]/*[local-name(.)='Object'][7]/*[local-name(.)='name'][1]"), XmlTypeCode.String, false);
            IVTDSetter actualValueSetter33 = new VTDCheckpointSetter(XmlTypeCode.String);
            BindDirection actualBindDirection33 = new BindDirection(_flow.HTTPActivity4, actualValueGetter33, actualValueSetter33);
            CpValObj valueActualObject33 = new CpValObj(actualBindDirection33, XmlTypeCode.String, false);
            CpValObj valueExpectedObject33 = new CpValObj("Devani Khatri", XmlTypeCode.String);
            ValueCPRule cpRule33 = new ValueCPRule(valueActualObject33, valueExpectedObject33, StringCP.EqualTo, "=", false);

            // Checkpoint 34
            IVTDGetter actualValueGetter34 = new VTDXPathGetter(new VTDPropertyInfoBase("XMLResponse", "/*[local-name(.)='Array'][1]/*[local-name(.)='Object'][7]/*[local-name(.)='email'][1]"), XmlTypeCode.String, false);
            IVTDSetter actualValueSetter34 = new VTDCheckpointSetter(XmlTypeCode.String);
            BindDirection actualBindDirection34 = new BindDirection(_flow.HTTPActivity4, actualValueGetter34, actualValueSetter34);
            CpValObj valueActualObject34 = new CpValObj(actualBindDirection34, XmlTypeCode.String, false);
            CpValObj valueExpectedObject34 = new CpValObj("khatri_devani@stanton.example", XmlTypeCode.String);
            ValueCPRule cpRule34 = new ValueCPRule(valueActualObject34, valueExpectedObject34, StringCP.EqualTo, "=", false);

            // Checkpoint 35
            IVTDGetter actualValueGetter35 = new VTDXPathGetter(new VTDPropertyInfoBase("XMLResponse", "/*[local-name(.)='Array'][1]/*[local-name(.)='Object'][7]/*[local-name(.)='gender'][1]"), XmlTypeCode.String, false);
            IVTDSetter actualValueSetter35 = new VTDCheckpointSetter(XmlTypeCode.String);
            BindDirection actualBindDirection35 = new BindDirection(_flow.HTTPActivity4, actualValueGetter35, actualValueSetter35);
            CpValObj valueActualObject35 = new CpValObj(actualBindDirection35, XmlTypeCode.String, false);
            CpValObj valueExpectedObject35 = new CpValObj("male", XmlTypeCode.String);
            ValueCPRule cpRule35 = new ValueCPRule(valueActualObject35, valueExpectedObject35, StringCP.EqualTo, "=", false);

            // Checkpoint 36
            IVTDGetter actualValueGetter36 = new VTDXPathGetter(new VTDPropertyInfoBase("XMLResponse", "/*[local-name(.)='Array'][1]/*[local-name(.)='Object'][7]/*[local-name(.)='status'][1]"), XmlTypeCode.String, false);
            IVTDSetter actualValueSetter36 = new VTDCheckpointSetter(XmlTypeCode.String);
            BindDirection actualBindDirection36 = new BindDirection(_flow.HTTPActivity4, actualValueGetter36, actualValueSetter36);
            CpValObj valueActualObject36 = new CpValObj(actualBindDirection36, XmlTypeCode.String, false);
            CpValObj valueExpectedObject36 = new CpValObj("active", XmlTypeCode.String);
            ValueCPRule cpRule36 = new ValueCPRule(valueActualObject36, valueExpectedObject36, StringCP.EqualTo, "=", false);

            // Checkpoint 37
            IVTDGetter actualValueGetter37 = new VTDXPathGetter(new VTDPropertyInfoBase("XMLResponse", "/*[local-name(.)='Array'][1]/*[local-name(.)='Object'][8]/*[local-name(.)='id'][1]"), XmlTypeCode.UnsignedInt, false);
            IVTDSetter actualValueSetter37 = new VTDCheckpointSetter(XmlTypeCode.UnsignedInt);
            BindDirection actualBindDirection37 = new BindDirection(_flow.HTTPActivity4, actualValueGetter37, actualValueSetter37);
            CpValObj valueActualObject37 = new CpValObj(actualBindDirection37, XmlTypeCode.UnsignedInt, false);
            CpValObj valueExpectedObject37 = new CpValObj("5816783", XmlTypeCode.UnsignedInt);
            ValueCPRule cpRule37 = new ValueCPRule(valueActualObject37, valueExpectedObject37, PrimitiveTypeCP.EqualTo, "=", false);

            // Checkpoint 38
            IVTDGetter actualValueGetter38 = new VTDXPathGetter(new VTDPropertyInfoBase("XMLResponse", "/*[local-name(.)='Array'][1]/*[local-name(.)='Object'][8]/*[local-name(.)='name'][1]"), XmlTypeCode.String, false);
            IVTDSetter actualValueSetter38 = new VTDCheckpointSetter(XmlTypeCode.String);
            BindDirection actualBindDirection38 = new BindDirection(_flow.HTTPActivity4, actualValueGetter38, actualValueSetter38);
            CpValObj valueActualObject38 = new CpValObj(actualBindDirection38, XmlTypeCode.String, false);
            CpValObj valueExpectedObject38 = new CpValObj("Kailash Khatri II", XmlTypeCode.String);
            ValueCPRule cpRule38 = new ValueCPRule(valueActualObject38, valueExpectedObject38, StringCP.EqualTo, "=", false);

            // Checkpoint 39
            IVTDGetter actualValueGetter39 = new VTDXPathGetter(new VTDPropertyInfoBase("XMLResponse", "/*[local-name(.)='Array'][1]/*[local-name(.)='Object'][8]/*[local-name(.)='email'][1]"), XmlTypeCode.String, false);
            IVTDSetter actualValueSetter39 = new VTDCheckpointSetter(XmlTypeCode.String);
            BindDirection actualBindDirection39 = new BindDirection(_flow.HTTPActivity4, actualValueGetter39, actualValueSetter39);
            CpValObj valueActualObject39 = new CpValObj(actualBindDirection39, XmlTypeCode.String, false);
            CpValObj valueExpectedObject39 = new CpValObj("ii_kailash_khatri@heidenreich.test", XmlTypeCode.String);
            ValueCPRule cpRule39 = new ValueCPRule(valueActualObject39, valueExpectedObject39, StringCP.EqualTo, "=", false);

            // Checkpoint 40
            IVTDGetter actualValueGetter40 = new VTDXPathGetter(new VTDPropertyInfoBase("XMLResponse", "/*[local-name(.)='Array'][1]/*[local-name(.)='Object'][8]/*[local-name(.)='gender'][1]"), XmlTypeCode.String, false);
            IVTDSetter actualValueSetter40 = new VTDCheckpointSetter(XmlTypeCode.String);
            BindDirection actualBindDirection40 = new BindDirection(_flow.HTTPActivity4, actualValueGetter40, actualValueSetter40);
            CpValObj valueActualObject40 = new CpValObj(actualBindDirection40, XmlTypeCode.String, false);
            CpValObj valueExpectedObject40 = new CpValObj("male", XmlTypeCode.String);
            ValueCPRule cpRule40 = new ValueCPRule(valueActualObject40, valueExpectedObject40, StringCP.EqualTo, "=", false);

            // Checkpoint 41
            IVTDGetter actualValueGetter41 = new VTDXPathGetter(new VTDPropertyInfoBase("XMLResponse", "/*[local-name(.)='Array'][1]/*[local-name(.)='Object'][8]/*[local-name(.)='status'][1]"), XmlTypeCode.String, false);
            IVTDSetter actualValueSetter41 = new VTDCheckpointSetter(XmlTypeCode.String);
            BindDirection actualBindDirection41 = new BindDirection(_flow.HTTPActivity4, actualValueGetter41, actualValueSetter41);
            CpValObj valueActualObject41 = new CpValObj(actualBindDirection41, XmlTypeCode.String, false);
            CpValObj valueExpectedObject41 = new CpValObj("active", XmlTypeCode.String);
            ValueCPRule cpRule41 = new ValueCPRule(valueActualObject41, valueExpectedObject41, StringCP.EqualTo, "=", false);

            // Checkpoint 42
            IVTDGetter actualValueGetter42 = new VTDXPathGetter(new VTDPropertyInfoBase("XMLResponse", "/*[local-name(.)='Array'][1]/*[local-name(.)='Object'][9]/*[local-name(.)='id'][1]"), XmlTypeCode.UnsignedInt, false);
            IVTDSetter actualValueSetter42 = new VTDCheckpointSetter(XmlTypeCode.UnsignedInt);
            BindDirection actualBindDirection42 = new BindDirection(_flow.HTTPActivity4, actualValueGetter42, actualValueSetter42);
            CpValObj valueActualObject42 = new CpValObj(actualBindDirection42, XmlTypeCode.UnsignedInt, false);
            CpValObj valueExpectedObject42 = new CpValObj("5816782", XmlTypeCode.UnsignedInt);
            ValueCPRule cpRule42 = new ValueCPRule(valueActualObject42, valueExpectedObject42, PrimitiveTypeCP.EqualTo, "=", false);

            // Checkpoint 43
            IVTDGetter actualValueGetter43 = new VTDXPathGetter(new VTDPropertyInfoBase("XMLResponse", "/*[local-name(.)='Array'][1]/*[local-name(.)='Object'][9]/*[local-name(.)='name'][1]"), XmlTypeCode.String, false);
            IVTDSetter actualValueSetter43 = new VTDCheckpointSetter(XmlTypeCode.String);
            BindDirection actualBindDirection43 = new BindDirection(_flow.HTTPActivity4, actualValueGetter43, actualValueSetter43);
            CpValObj valueActualObject43 = new CpValObj(actualBindDirection43, XmlTypeCode.String, false);
            CpValObj valueExpectedObject43 = new CpValObj("Maheswar Adiga DC", XmlTypeCode.String);
            ValueCPRule cpRule43 = new ValueCPRule(valueActualObject43, valueExpectedObject43, StringCP.EqualTo, "=", false);

            // Checkpoint 44
            IVTDGetter actualValueGetter44 = new VTDXPathGetter(new VTDPropertyInfoBase("XMLResponse", "/*[local-name(.)='Array'][1]/*[local-name(.)='Object'][9]/*[local-name(.)='email'][1]"), XmlTypeCode.String, false);
            IVTDSetter actualValueSetter44 = new VTDCheckpointSetter(XmlTypeCode.String);
            BindDirection actualBindDirection44 = new BindDirection(_flow.HTTPActivity4, actualValueGetter44, actualValueSetter44);
            CpValObj valueActualObject44 = new CpValObj(actualBindDirection44, XmlTypeCode.String, false);
            CpValObj valueExpectedObject44 = new CpValObj("adiga_dc_maheswar@marvin.example", XmlTypeCode.String);
            ValueCPRule cpRule44 = new ValueCPRule(valueActualObject44, valueExpectedObject44, StringCP.EqualTo, "=", false);

            // Checkpoint 45
            IVTDGetter actualValueGetter45 = new VTDXPathGetter(new VTDPropertyInfoBase("XMLResponse", "/*[local-name(.)='Array'][1]/*[local-name(.)='Object'][9]/*[local-name(.)='gender'][1]"), XmlTypeCode.String, false);
            IVTDSetter actualValueSetter45 = new VTDCheckpointSetter(XmlTypeCode.String);
            BindDirection actualBindDirection45 = new BindDirection(_flow.HTTPActivity4, actualValueGetter45, actualValueSetter45);
            CpValObj valueActualObject45 = new CpValObj(actualBindDirection45, XmlTypeCode.String, false);
            CpValObj valueExpectedObject45 = new CpValObj("male", XmlTypeCode.String);
            ValueCPRule cpRule45 = new ValueCPRule(valueActualObject45, valueExpectedObject45, StringCP.EqualTo, "=", false);

            // Checkpoint 46
            IVTDGetter actualValueGetter46 = new VTDXPathGetter(new VTDPropertyInfoBase("XMLResponse", "/*[local-name(.)='Array'][1]/*[local-name(.)='Object'][9]/*[local-name(.)='status'][1]"), XmlTypeCode.String, false);
            IVTDSetter actualValueSetter46 = new VTDCheckpointSetter(XmlTypeCode.String);
            BindDirection actualBindDirection46 = new BindDirection(_flow.HTTPActivity4, actualValueGetter46, actualValueSetter46);
            CpValObj valueActualObject46 = new CpValObj(actualBindDirection46, XmlTypeCode.String, false);
            CpValObj valueExpectedObject46 = new CpValObj("inactive", XmlTypeCode.String);
            ValueCPRule cpRule46 = new ValueCPRule(valueActualObject46, valueExpectedObject46, StringCP.EqualTo, "=", false);

            // Checkpoint 47
            IVTDGetter actualValueGetter47 = new VTDXPathGetter(new VTDPropertyInfoBase("XMLResponse", "/*[local-name(.)='Array'][1]/*[local-name(.)='Object'][10]/*[local-name(.)='id'][1]"), XmlTypeCode.UnsignedInt, false);
            IVTDSetter actualValueSetter47 = new VTDCheckpointSetter(XmlTypeCode.UnsignedInt);
            BindDirection actualBindDirection47 = new BindDirection(_flow.HTTPActivity4, actualValueGetter47, actualValueSetter47);
            CpValObj valueActualObject47 = new CpValObj(actualBindDirection47, XmlTypeCode.UnsignedInt, false);
            CpValObj valueExpectedObject47 = new CpValObj("5816781", XmlTypeCode.UnsignedInt);
            ValueCPRule cpRule47 = new ValueCPRule(valueActualObject47, valueExpectedObject47, PrimitiveTypeCP.EqualTo, "=", false);

            // Checkpoint 48
            IVTDGetter actualValueGetter48 = new VTDXPathGetter(new VTDPropertyInfoBase("XMLResponse", "/*[local-name(.)='Array'][1]/*[local-name(.)='Object'][10]/*[local-name(.)='name'][1]"), XmlTypeCode.String, false);
            IVTDSetter actualValueSetter48 = new VTDCheckpointSetter(XmlTypeCode.String);
            BindDirection actualBindDirection48 = new BindDirection(_flow.HTTPActivity4, actualValueGetter48, actualValueSetter48);
            CpValObj valueActualObject48 = new CpValObj(actualBindDirection48, XmlTypeCode.String, false);
            CpValObj valueExpectedObject48 = new CpValObj("Deeptimay Nehru", XmlTypeCode.String);
            ValueCPRule cpRule48 = new ValueCPRule(valueActualObject48, valueExpectedObject48, StringCP.EqualTo, "=", false);

            // Checkpoint 49
            IVTDGetter actualValueGetter49 = new VTDXPathGetter(new VTDPropertyInfoBase("XMLResponse", "/*[local-name(.)='Array'][1]/*[local-name(.)='Object'][10]/*[local-name(.)='email'][1]"), XmlTypeCode.String, false);
            IVTDSetter actualValueSetter49 = new VTDCheckpointSetter(XmlTypeCode.String);
            BindDirection actualBindDirection49 = new BindDirection(_flow.HTTPActivity4, actualValueGetter49, actualValueSetter49);
            CpValObj valueActualObject49 = new CpValObj(actualBindDirection49, XmlTypeCode.String, false);
            CpValObj valueExpectedObject49 = new CpValObj("nehru_deeptimay@rolfson-braun.example", XmlTypeCode.String);
            ValueCPRule cpRule49 = new ValueCPRule(valueActualObject49, valueExpectedObject49, StringCP.EqualTo, "=", false);

            // Checkpoint 50
            IVTDGetter actualValueGetter50 = new VTDXPathGetter(new VTDPropertyInfoBase("XMLResponse", "/*[local-name(.)='Array'][1]/*[local-name(.)='Object'][10]/*[local-name(.)='gender'][1]"), XmlTypeCode.String, false);
            IVTDSetter actualValueSetter50 = new VTDCheckpointSetter(XmlTypeCode.String);
            BindDirection actualBindDirection50 = new BindDirection(_flow.HTTPActivity4, actualValueGetter50, actualValueSetter50);
            CpValObj valueActualObject50 = new CpValObj(actualBindDirection50, XmlTypeCode.String, false);
            CpValObj valueExpectedObject50 = new CpValObj("female", XmlTypeCode.String);
            ValueCPRule cpRule50 = new ValueCPRule(valueActualObject50, valueExpectedObject50, StringCP.EqualTo, "=", false);

            // Checkpoint 51
            IVTDGetter actualValueGetter51 = new VTDXPathGetter(new VTDPropertyInfoBase("XMLResponse", "/*[local-name(.)='Array'][1]/*[local-name(.)='Object'][10]/*[local-name(.)='status'][1]"), XmlTypeCode.String, false);
            IVTDSetter actualValueSetter51 = new VTDCheckpointSetter(XmlTypeCode.String);
            BindDirection actualBindDirection51 = new BindDirection(_flow.HTTPActivity4, actualValueGetter51, actualValueSetter51);
            CpValObj valueActualObject51 = new CpValObj(actualBindDirection51, XmlTypeCode.String, false);
            CpValObj valueExpectedObject51 = new CpValObj("inactive", XmlTypeCode.String);
            ValueCPRule cpRule51 = new ValueCPRule(valueActualObject51, valueExpectedObject51, StringCP.EqualTo, "=", false);

            ArrayElementCPRule arrayElementCPRule1 = new ArrayElementCPRule();
            ArrayBaseCPRule arrayFixedCpRule1 = new ArrayFixedCPRule("/*[local-name(.)='Array'][1]/*[local-name(.)='Object']", HandlerType.XML);
            ArrayElementCPRule arrayElementCPRule2 = new ArrayElementCPRule();
            ArrayElementCPRule arrayElementCPRule3 = new ArrayElementCPRule();
            ArrayElementCPRule arrayElementCPRule4 = new ArrayElementCPRule();
            ArrayElementCPRule arrayElementCPRule5 = new ArrayElementCPRule();
            ArrayElementCPRule arrayElementCPRule6 = new ArrayElementCPRule();
            ArrayElementCPRule arrayElementCPRule7 = new ArrayElementCPRule();
            ArrayElementCPRule arrayElementCPRule8 = new ArrayElementCPRule();
            ArrayElementCPRule arrayElementCPRule9 = new ArrayElementCPRule();
            ArrayElementCPRule arrayElementCPRule10 = new ArrayElementCPRule();
            arrayElementCPRule1.AddRule(cpRule2);
            arrayElementCPRule1.AddRule(cpRule3);
            arrayElementCPRule1.AddRule(cpRule4);
            arrayElementCPRule1.AddRule(cpRule5);
            arrayElementCPRule1.AddRule(cpRule6);
            arrayFixedCpRule1.AddRule(arrayElementCPRule1);
            arrayFixedCpRule1.AddRule(arrayElementCPRule2);
            arrayFixedCpRule1.AddRule(arrayElementCPRule3);
            arrayFixedCpRule1.AddRule(arrayElementCPRule4);
            arrayFixedCpRule1.AddRule(arrayElementCPRule5);
            arrayFixedCpRule1.AddRule(arrayElementCPRule6);
            arrayFixedCpRule1.AddRule(arrayElementCPRule7);
            arrayFixedCpRule1.AddRule(arrayElementCPRule8);
            arrayFixedCpRule1.AddRule(arrayElementCPRule9);
            arrayFixedCpRule1.AddRule(arrayElementCPRule10);
            arrayElementCPRule2.AddRule(cpRule7);
            arrayElementCPRule2.AddRule(cpRule8);
            arrayElementCPRule2.AddRule(cpRule9);
            arrayElementCPRule2.AddRule(cpRule10);
            arrayElementCPRule2.AddRule(cpRule11);
            arrayElementCPRule3.AddRule(cpRule12);
            arrayElementCPRule3.AddRule(cpRule13);
            arrayElementCPRule3.AddRule(cpRule14);
            arrayElementCPRule3.AddRule(cpRule15);
            arrayElementCPRule3.AddRule(cpRule16);
            arrayElementCPRule4.AddRule(cpRule17);
            arrayElementCPRule4.AddRule(cpRule18);
            arrayElementCPRule4.AddRule(cpRule19);
            arrayElementCPRule4.AddRule(cpRule20);
            arrayElementCPRule4.AddRule(cpRule21);
            arrayElementCPRule5.AddRule(cpRule22);
            arrayElementCPRule5.AddRule(cpRule23);
            arrayElementCPRule5.AddRule(cpRule24);
            arrayElementCPRule5.AddRule(cpRule25);
            arrayElementCPRule5.AddRule(cpRule26);
            arrayElementCPRule6.AddRule(cpRule27);
            arrayElementCPRule6.AddRule(cpRule28);
            arrayElementCPRule6.AddRule(cpRule29);
            arrayElementCPRule6.AddRule(cpRule30);
            arrayElementCPRule6.AddRule(cpRule31);
            arrayElementCPRule7.AddRule(cpRule32);
            arrayElementCPRule7.AddRule(cpRule33);
            arrayElementCPRule7.AddRule(cpRule34);
            arrayElementCPRule7.AddRule(cpRule35);
            arrayElementCPRule7.AddRule(cpRule36);
            arrayElementCPRule8.AddRule(cpRule37);
            arrayElementCPRule8.AddRule(cpRule38);
            arrayElementCPRule8.AddRule(cpRule39);
            arrayElementCPRule8.AddRule(cpRule40);
            arrayElementCPRule8.AddRule(cpRule41);
            arrayElementCPRule9.AddRule(cpRule42);
            arrayElementCPRule9.AddRule(cpRule43);
            arrayElementCPRule9.AddRule(cpRule44);
            arrayElementCPRule9.AddRule(cpRule45);
            arrayElementCPRule9.AddRule(cpRule46);
            arrayElementCPRule10.AddRule(cpRule47);
            arrayElementCPRule10.AddRule(cpRule48);
            arrayElementCPRule10.AddRule(cpRule49);
            arrayElementCPRule10.AddRule(cpRule50);
            arrayElementCPRule10.AddRule(cpRule51);
            activity.AddCheckpointRule(arrayFixedCpRule1);
        }
    }
}
